# Generated by Django 3.1.5 on 2021-01-14 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genrename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'genres',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=255)),
                ('Employer', models.CharField(max_length=255)),
                ('JobURL', models.URLField(blank=True, null=True)),
                ('JobLevel', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Availability', models.DateField()),
                ('Description', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'db_table': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articletitle', models.CharField(max_length=255)),
                ('articledescription', models.CharField(blank=True, max_length=255, null=True)),
                ('articleurl', models.CharField(blank=True, max_length=255, null=True)),
                ('articledate', models.DateField(null=True)),
                ('articlegenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.genre')),
                ('articleuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'articles',
                'db_table': 'article',
            },
        ),
    ]
